 SELECT "MBUCFPRENAME"."PRENAME_DESC",   
         "MBUCFMEMBGROUP_A"."MEMBGROUP_DESC",   
         "MBMEMBMASTER"."MEMB_NAME",   
         "MBMEMBMASTER"."MEMB_SURNAME",   
         "MBMEMBMASTER"."MEMBGROUP_CODE",   
         "MBMEMBMASTER"."BIRTH_DATE",   
         "MBMEMBMASTER"."MEMBER_DATE",   
         "MBMEMBMASTER"."CARD_PERSON",   
         "MBMEMBMASTER"."MATE_NAME",   
         "MBMEMBMASTER"."SALARY_AMOUNT",   
         "LNUCFLOANOBJECTIVE"."LOANOBJECTIVE_DESC",   
         "LNREQLOAN"."MEMBER_NO",   
         "LNREQLOAN"."LOANTYPE_CODE",   
         "LNREQLOAN"."LOANREQUEST_DATE",   
         "LNREQLOAN"."LOANCREDIT_AMT",   
         "LNREQLOAN"."LOANPERMISS_AMT",   
         "LNREQLOAN"."LOANREQUEST_AMT",   
         "LNREQLOAN"."LOANPAYMENT_TYPE",   
         "LNREQLOAN"."PERIOD_PAYMENT",   
         "LNREQLOAN"."LOANCONTRACT_NO",   
         "LNREQLOAN"."STARTKEEP_DATE",   
         "LNREQLOAN"."PERIOD_PAYAMT",   
         "MBUCFMEMBGROUP_B"."MEMBGROUP_DESC" as groupcontrol_desc,   
         "LNREQLOAN"."LOANREQUEST_DOCNO"  
    FROM "LNREQLOAN",   
         "LNUCFLOANOBJECTIVE",   
         "MBMEMBMASTER",   
         "MBUCFMEMBGROUP" "MBUCFMEMBGROUP_A",   
         "MBUCFPRENAME",   
         "MBUCFMEMBGROUP" "MBUCFMEMBGROUP_B"  
   WHERE ( "MBUCFMEMBGROUP_A"."COOP_ID" = "MBMEMBMASTER"."COOP_ID" ) and  
         ( "MBUCFMEMBGROUP_A"."MEMBGROUP_CODE" = "MBMEMBMASTER"."MEMBGROUP_CODE" ) and  
         ( "MBUCFPRENAME"."PRENAME_CODE" = "MBMEMBMASTER"."PRENAME_CODE" ) and  
         ( "LNREQLOAN"."COOP_ID" = "LNUCFLOANOBJECTIVE"."COOP_ID" ) and  
         ( "LNREQLOAN"."LOANTYPE_CODE" = "LNUCFLOANOBJECTIVE"."LOANTYPE_CODE" ) and  
         ( "LNREQLOAN"."LOANOBJECTIVE_CODE" = "LNUCFLOANOBJECTIVE"."LOANOBJECTIVE_CODE" ) and  
         ( "LNREQLOAN"."MEMBER_NO" = "MBMEMBMASTER"."MEMBER_NO" ) and  
         ( "LNREQLOAN"."COOP_ID" = "MBMEMBMASTER"."COOP_ID" ) and  
         ( "MBUCFMEMBGROUP_A"."COOP_ID" = "MBUCFMEMBGROUP_B"."COOP_ID" ) and  
         ( "MBUCFMEMBGROUP_A"."MEMBGROUP_CONTROL" = "MBUCFMEMBGROUP_B"."MEMBGROUP_CODE" ) and  
         ( ( "LNREQLOAN"."LOANREQUEST_DOCNO" ='333' ) )    
