//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saving.Applications.shrlon.ws_convert_txt2db_ctrl {
    
    
    public partial class ws_convert_txt2db {
        
        /// <summary>
        /// txtInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload txtInput;
        
        /// <summary>
        /// dsHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.ws_convert_txt2db_ctrl.DsHeader dsHeader;
        
        /// <summary>
        /// dsDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.ws_convert_txt2db_ctrl.DsDetail dsDetail;
        
        /// <summary>
        /// dsDetailFail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.ws_convert_txt2db_ctrl.DsDetailFail dsDetailFail;
        
        /// <summary>
        /// dsTailer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.ws_convert_txt2db_ctrl.DsTailer dsTailer;
        
        /// <summary>
        /// dsDetailFinish control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.ws_convert_txt2db_ctrl.DsDetailFinish dsDetailFinish;
        
        /// <summary>
        /// dsMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.ws_convert_txt2db_ctrl.DsMain dsMain;
        
        /// <summary>
        /// dsDetailEtc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.ws_convert_txt2db_ctrl.DsDetailEtc dsDetailEtc;
        
        /// <summary>
        /// dsDetailShare control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.ws_convert_txt2db_ctrl.DsDetailShare dsDetailShare;
        
        /// <summary>
        /// dsDetailLoan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.ws_convert_txt2db_ctrl.DsDetailLoan dsDetailLoan;
    }
}
