//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saving.Applications.shrlon.w_sheet_ln_nplmaster_ctrl {
    
    
    public partial class w_sheet_ln_nplmaster {
        
        /// <summary>
        /// dsMemb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.w_sheet_ln_nplmaster_ctrl.DsMemb dsMemb;
        
        /// <summary>
        /// dsLoan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.w_sheet_ln_nplmaster_ctrl.DsLoan dsLoan;
        
        /// <summary>
        /// dsNPL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.w_sheet_ln_nplmaster_ctrl.DsNPL dsNPL;
        
        /// <summary>
        /// dsFollowMast control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.w_sheet_ln_nplmaster_ctrl.DsFollowMast dsFollowMast;
        
        /// <summary>
        /// dsFollow1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.w_sheet_ln_nplmaster_ctrl.DsFollow dsFollow1;
        
        /// <summary>
        /// dsFollow2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.w_sheet_ln_nplmaster_ctrl.DsFollow dsFollow2;
        
        /// <summary>
        /// dsBoard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.w_sheet_ln_nplmaster_ctrl.DsBoard dsBoard;
        
        /// <summary>
        /// dsResolution control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.w_sheet_ln_nplmaster_ctrl.DsResolution dsResolution;
        
        /// <summary>
        /// dsMort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.w_sheet_ln_nplmaster_ctrl.DsMort dsMort;
        
        /// <summary>
        /// dsColl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.w_sheet_ln_nplmaster_ctrl.DsColl dsColl;
        
        /// <summary>
        /// dsCollSub control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.shrlon.w_sheet_ln_nplmaster_ctrl.DsCollSub dsCollSub;
        
        /// <summary>
        /// hdTabIndex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdTabIndex;
    }
}
