CREATE TABLE "COOP" ("COOP_ID" CHAR(4) NOT NULL, "COOP_DESC" VARCHAR2(300) NOT NULL, "SAVING_ACC" CHAR(15) NOT NULL, "PXCREDIT" NUMBER(1,0) DEFAULT 0 NOT NULL, "WITHCREDIT" NUMBER(1,0) DEFAULT 0 NOT NULL, "COOPHOLD" NUMBER(1,0) DEFAULT 0 NOT NULL, "COOP_PWD" VARCHAR2(20), "ADMIN_FLAG" NUMBER(1,0) DEFAULT 0, "START_DATE" DATE, "ENCRYPT_FLAG" NUMBER(1,0) DEFAULT 0, "HEADERTAILER_FLAG" NUMBER(1,0) DEFAULT 0, "EXPORTPAY_FLAG" NUMBER(1,0) DEFAULT 0, "PAY_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL, "WITHDRAW_FLAG" NUMBER(1,0) DEFAULT 1 NOT NULL, "DEPTSEQUEST_AMT" NUMBER(15,2) DEFAULT 0, "TOFROMACCID" VARCHAR2(10), "BANK_POSTFIX" CHAR(2), "GENBF_STATUS" NUMBER(2,0) DEFAULT '0' NOT NULL, "COOPHOLD_DATE" DATE) ;
ALTER TABLE "COOP" ADD ( CONSTRAINT XPCOOP PRIMARY KEY ( "COOP_ID" )) ;
INSERT INTO COOP
VALUES('2500', 'COOP' , '0123456789' , 1, 1 , 0, '' , 0, sysdate , 0 , 0 , 0, 0, 1, 0 , '2111000' , '' , 0, NULL ) ;

CREATE TABLE "MEMBER" ("MEMBER_NO" CHAR(8) NOT NULL, "COOP_ID" CHAR(4) NOT NULL, "NAME" VARCHAR2(90), "SURNAME" VARCHAR2(90), "PERSON_ID" CHAR(13)) ;
ALTER TABLE "MEMBER" ADD ( CONSTRAINT XPMEMBER PRIMARY KEY ( "MEMBER_NO", "COOP_ID" )) ;
CREATE INDEX "XIF1MEMBER" ON "MEMBER" ("COOP_ID" ) ;

CREATE TABLE "ATMDEPT" ("MEMBER_NO" CHAR(8) NOT NULL, "COOP_ID" CHAR(4) NOT NULL, "COOP_ACC" CHAR(45) NOT NULL, "WITHATM_AMT" NUMBER(15,2) DEFAULT 0 NOT NULL, "BALANCE_AMT" NUMBER(15,2) DEFAULT 0 NOT NULL, "RECEIVE_AMT" NUMBER(15,2) DEFAULT 0 NOT NULL, "PAY_AMT" NUMBER(15,2) DEFAULT 0 NOT NULL, "SAVING_ACC" CHAR(15) NOT NULL, "DEPTHOLD" NUMBER(1,0) DEFAULT 0 NOT NULL, "POST_FLAG" CHAR(1) DEFAULT 1, "DEPTTYPE_CODE" CHAR(2) DEFAULT '88' NOT NULL, "SEQUEST_AMT" NUMBER(15,2) DEFAULT 0 NOT NULL) ;
ALTER TABLE "ATMDEPT" ADD ( CONSTRAINT XPATMDEPT PRIMARY KEY ( "MEMBER_NO", "COOP_ID", "COOP_ACC" )) ;
CREATE INDEX "XIF3ATMDEPT" ON "ATMDEPT" ("SAVING_ACC" ) ;
CREATE INDEX "XIF2ATMDEPT" ON "ATMDEPT" ("MEMBER_NO" ) ;

CREATE TABLE "ATMLOAN" ("MEMBER_NO" CHAR(8) NOT NULL, "COOP_ID" CHAR(4) NOT NULL, "CONTRACT_NO" VARCHAR2(45) NOT NULL, "CREDIT_AMT" NUMBER(15,2) DEFAULT 0 NOT NULL, "BALANCE_AMT" NUMBER(15,2) DEFAULT 0 NOT NULL, "RECEIVE_AMT" NUMBER(15,2) DEFAULT 0 NOT NULL, "PAY_AMT" NUMBER(15,2) DEFAULT 0 NOT NULL, "SAVING_ACC" CHAR(15) NOT NULL, "LOANHOLD" NUMBER(1,0) DEFAULT 0 NOT NULL, "POST_FLAG" CHAR(1) DEFAULT 1, "LOANTYPE_CODE" CHAR(2) DEFAULT '88' NOT NULL) ;
ALTER TABLE "ATMLOAN" ADD ( CONSTRAINT XPATMLOAN PRIMARY KEY ( "MEMBER_NO", "COOP_ID", "CONTRACT_NO" )) ;
CREATE INDEX "XIF3ATMLOAN" ON "ATMLOAN" ("SAVING_ACC" ) ;
CREATE INDEX "XIF1ATMLOAN" ON "ATMLOAN" ("MEMBER_NO" ) ;

CREATE TABLE "ATM_TRANS" ("COOP_ID" CHAR(4) NOT NULL, "MEMNO" CHAR(8) NOT NULL, "SEQNO" FLOAT NOT NULL, "OPERATEDATE" DATE, "FINTYPE" CHAR(1), "OPERATECD" CHAR(3) NOT NULL, "SYSTEMCD" CHAR(2) NOT NULL, "BANKCD" CHAR(3), "BRANCHCD" CHAR(3), "ATMNO" VARCHAR2(12) NOT NULL, "ATMSEQNO" VARCHAR2(8) NOT NULL, "ACCNO" CHAR(15), "ITEMAMT" NUMBER(17,5), "ISPOST" CHAR(1), "POSTDATE" DATE, "TRANSSTS" CHAR(1) DEFAULT 'W', "ISREC" CHAR(1), "RECONDATE" DATE, "STAMPDATE" DATE DEFAULT sysdate) ;
ALTER TABLE "ATM_TRANS" ADD ( CONSTRAINT XPKATM_TRANSACTIONS PRIMARY KEY ( "COOP_ID", "MEMNO", "SEQNO", "ATMNO", "ATMSEQNO", "OPERATECD", "SYSTEMCD" )) ;

CREATE TABLE "ATM_TRANS_POST_SCSS" ("COOP_ID" CHAR(4) NOT NULL, "MEMNO" CHAR(8) NOT NULL, "SEQNO" FLOAT NOT NULL, "OPERATEDATE" DATE, "FINTYPE" CHAR(1), "OPERATECD" CHAR(3), "SYSTEMCD" CHAR(2) NOT NULL, "BANKCD" CHAR(3), "BRANCHCD" CHAR(3), "ATMNO" VARCHAR2(12), "ATMSEQNO" VARCHAR2(8), "ACCNO" CHAR(15), "ITEMAMT" NUMBER(17,5), "ISPOST" CHAR(1), "POSTDATE" DATE, "TRANSSTS" CHAR(1) DEFAULT 'W', "ISREC" CHAR(1), "RECONDATE" DATE, "STAMPDATE" DATE DEFAULT sysdate) ;
ALTER TABLE "ATM_TRANS_POST_SCSS" ADD ( CONSTRAINT XPKATM_TRANSACTIONS_POST_SUCCE PRIMARY KEY ( "COOP_ID", "MEMNO", "SEQNO" )) ;

CREATE TABLE "ATMACT" ("CCS_OPERATE_DATE" DATE NOT NULL, "ATM_NO" CHAR(12) NOT NULL, "ATM_SEQNO" CHAR(8) NOT NULL, "OPERATE_DATE" DATE NOT NULL, "COOP_ID" CHAR(4) NOT NULL, "COOP_SAVING_ACC" CHAR(15), "CCS_COOP_SAVING_ACC" CHAR(15), "MEMBER_NO" CHAR(8), "SAVING_ACC" CHAR(15) NOT NULL, "SYSTEM_CODE" CHAR(2) NOT NULL, "OPERATE_CODE" CHAR(3) NOT NULL, "TRANSACTION_AMT" NUMBER(15,2) DEFAULT 0 NOT NULL, "BANK_CODE" CHAR(3) NOT NULL, "BRANCH_CODE" CHAR(3) NOT NULL, "CREDIT_AMT" NUMBER(15,2) DEFAULT 0 NOT NULL, "BALANCE_AMT" NUMBER(15,2) DEFAULT 0 NOT NULL, "RESPONSE_CODE" CHAR(4) NOT NULL, "REQUEST" VARCHAR2(80) NOT NULL, "RESPONSE" VARCHAR2(80) NOT NULL, "TRANS_CODE" VARCHAR2(4)) ;
ALTER TABLE "ATMACT" ADD ( CONSTRAINT XPKATMACT PRIMARY KEY ( "CCS_OPERATE_DATE", "ATM_NO", "ATM_SEQNO", "OPERATE_DATE" , "SYSTEM_CODE" , "OPERATE_CODE"  )) ;
CREATE INDEX "XIF2ATMACT" ON "ATMACT" ("MEMBER_NO" ) ;

CREATE TABLE "ATMCREDITHISTORY" ("IMPORT_FILE" CHAR(20) NOT NULL, "IMPORT_SEQ" NUMBER(15,0) NOT NULL, "IMPORT_DATE" DATE NOT NULL, "IMPORT_PERIOD" CHAR(4) NOT NULL, "ACCOUNT_NO" CHAR(10), "ITEM_TYPE" CHAR(1), "ITEM_AMOUNT" NUMBER(15,2), "OPERATE_DATE" DATE, "MEMBER_NO" CHAR(8), "BALANCE_AMOUNT" NUMBER(15,2), "EXPIRE_DATE" DATE, "REFERENCE_KEY" CHAR(45), "ACCOUNT_TYPE" CHAR(1), "COOP_ID" CHAR(4)) ;
ALTER TABLE "ATMCREDITHISTORY" ADD ( CONSTRAINT XPKATMCREDITHISTORY PRIMARY KEY ( "IMPORT_FILE", "IMPORT_SEQ", "IMPORT_DATE", "IMPORT_PERIOD" )) ;

CREATE TABLE "ATMCREDITMAX" ("MEMBER_NO" CHAR(8) NOT NULL, "SAVING_ACC" CHAR(15) NOT NULL, "CREDIT_MAX" NUMBER(15,2) NOT NULL) ;
ALTER TABLE "ATMCREDITMAX" ADD ( CONSTRAINT XPATMCREDITMAX PRIMARY KEY ( "SAVING_ACC" )) ;

CREATE TABLE "ATMRECOVERHISTORY" ("MEMBER_NO" CHAR(8) NOT NULL, "COOP_ID" CHAR(4) NOT NULL, "CCS_OPERATE_DATE" DATE NOT NULL, "OPERATE_DATE" DATE NOT NULL, "RECONCILE_DATE" DATE NOT NULL, "NEWOPERATE_DATE" DATE NOT NULL, "RECOVER_DATE" DATE) ;
ALTER TABLE "ATMRECOVERHISTORY" ADD ( CONSTRAINT XPATMRECOVERHISTORY PRIMARY KEY ( "MEMBER_NO", "COOP_ID", "CCS_OPERATE_DATE" )) ;

CREATE TABLE "ATMSAVINGACCHISTORY" ("IMPORT_FILE" CHAR(20) NOT NULL, "IMPORT_SEQ" NUMBER(15,0) NOT NULL, "IMPORT_DATE" DATE NOT NULL, "COOP_ID" CHAR(4) NOT NULL, "MEMBER_NO" CHAR(8) NOT NULL, "CONTRACT_NO" CHAR(45) NOT NULL, "SAVING_ACC_OLD" CHAR(15) NOT NULL, "SAVING_ACC_NEW" CHAR(15) NOT NULL, "SYSTEM_CODE" CHAR(2) DEFAULT '01') ;
ALTER TABLE "ATMSAVINGACCHISTORY" ADD ( CONSTRAINT XPATMSAVINGACCHISTORY PRIMARY KEY ( "IMPORT_FILE", "IMPORT_SEQ", "IMPORT_DATE" )) ;

CREATE TABLE "ATMSQL" ("ATMSQL" CLOB NOT NULL, "SQLDATE" DATE) ;

CREATE TABLE "ATMTOBANKHISTORY" ("POST_DATE" DATE NOT NULL, "POST_SEQ" NUMBER(8,0) NOT NULL, "SAVING_ACC" VARCHAR2(15), "COOP_ID" CHAR(4), "MEMBER_NO" CHAR(8), "ACCOUNT_TYPE" CHAR(1), "ACTION" CHAR(1)) ;
ALTER TABLE "ATMTOBANKHISTORY" ADD ( CONSTRAINT XPATMTOBANKHISTORY PRIMARY KEY ( "POST_DATE", "POST_SEQ" )) ;

CREATE TABLE "ATMTRANMASTER" ("MEMBER_NO" CHAR(8) NOT NULL, "COOP_ID" CHAR(4) NOT NULL, "CCS_OPERATE_DATE" DATE NOT NULL, "OPERATE_DATE" DATE, "SYSTEM_CODE" CHAR(2), "OPERATE_CODE" CHAR(3), "ITEM_AMT" NUMBER(15,2), "BANK_CODE" CHAR(3), "BRANCH_CODE" CHAR(3), "ATM_NO" CHAR(12), "ATM_SEQNO" CHAR(8), "POST_DATE" DATE, "SAVING_ACC" CHAR(15), "EXPORT_DATE" DATE) ;
ALTER TABLE "ATMTRANMASTER" ADD ( CONSTRAINT XPATMTRANMASTER PRIMARY KEY ( "MEMBER_NO", "COOP_ID", "CCS_OPERATE_DATE" )) ;
CREATE INDEX "XIF1ATMTRANMASTER" ON "ATMTRANMASTER" ("MEMBER_NO" ) ;
CREATE INDEX "XIF2ATMTRANMASTER" ON "ATMTRANMASTER" ("COOP_ID" ) ;

CREATE TABLE "ATMTRANSACTION" ("MEMBER_NO" CHAR(8) NOT NULL, "COOP_ID" CHAR(4) NOT NULL, "CCS_OPERATE_DATE" DATE NOT NULL, "OPERATE_DATE" DATE NOT NULL, "SYSTEM_CODE" CHAR(2) NOT NULL, "OPERATE_CODE" CHAR(3) NOT NULL, "ITEM_AMT" NUMBER(15,2) NOT NULL, "BANK_CODE" CHAR(3) NOT NULL, "BRANCH_CODE" CHAR(3) NOT NULL, "ATM_NO" VARCHAR2(12) NOT NULL, "ATM_SEQNO" VARCHAR2(8) NOT NULL, "ITEM_STATUS" NUMBER(1,0) DEFAULT 0 NOT NULL, "POST_STATUS" NUMBER(1,0) DEFAULT 0 NOT NULL, "POST_DATE" DATE, "SAVING_ACC" VARCHAR2(15) NOT NULL, "EXPORT_STATUS" NUMBER(1,0) DEFAULT 0, "EXPORT_DATE" DATE, "RECONCILE_DATE" DATE, "TRANS_CODE" VARCHAR2(4)) ;
ALTER TABLE "ATMTRANSACTION" ADD ( CONSTRAINT SYS_C006027 PRIMARY KEY ( "MEMBER_NO", "COOP_ID", "CCS_OPERATE_DATE" ,"OPERATE_DATE" , "SYSTEM_CODE" , "OPERATE_CODE" , "ATM_SEQNO" , "ATM_NO" )) ;
CREATE INDEX "XIF3ATMTRANSACTION" ON "ATMTRANSACTION" ("CCS_OPERATE_DATE" , "ATM_NO" , "ATM_SEQNO" ) ;
CREATE INDEX "XIF2ATMTRANSACTION" ON "ATMTRANSACTION" ("COOP_ID" ) ;
CREATE INDEX "XIF1ATMTRANSACTION" ON "ATMTRANSACTION" ("MEMBER_NO" ) ;
CREATE INDEX "ATMTRANSACTION_INX" ON "ATMTRANSACTION" ("OPERATE_DATE" , "SYSTEM_CODE" , "OPERATE_CODE" , "ATM_SEQNO" , "ATM_NO" ) ;

CREATE TABLE "PASSWORD_HISTORY" ("USER_ID" VARCHAR2(5) NOT NULL, "CHANGE_DATE" DATE NOT NULL, "PASSWORD" VARCHAR2(20)) ;
ALTER TABLE "PASSWORD_HISTORY" ADD ( CONSTRAINT XPPASSWORD_HISTORY PRIMARY KEY ( "USER_ID", "CHANGE_DATE" )) ;

CREATE TABLE "SECUSER" ("USER_ID" NUMBER(4,0) NOT NULL, "USER_NAME" VARCHAR2(30) NOT NULL, "FULL_NAME" VARCHAR2(100) NOT NULL, "DESCRIPTION" VARCHAR2(200), "EMP_NO" VARCHAR2(20), "LEVEL_NO" NUMBER(4,0), "HOLD_FLAG" NUMBER(1,0), "PASSWORD" VARCHAR2(20)) ;
ALTER TABLE "SECUSER" ADD ( CONSTRAINT SECUSERPK PRIMARY KEY ( "USER_ID" )) ;
