drop database link ATMSERV.REGRESS.RDBMS.DEV.US.ORACLE.COM;
CREATE DATABASE LINK "ATMSERV.REGRESS.RDBMS.DEV.US.ORACLE.COM" CONNECT TO "CORECOOP" IDENTIFIED BY corecoop USING '192.168.1.206/corecoop';
create or replace synonym PKG_ATMMGMT2 for CORECOOP.PKG_ATMMGMT2@ATMSERV.REGRESS.RDBMS.DEV.US.ORACLE.COM;
ALTER PACKAGE PKG_ATMMGMT COMPILE BODY; 
