//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saving.Applications.admin.w_sheet_am_amsecwins_ctrl.w_dlg_ad_test_ctrl {
    
    
    public partial class w_dlg_ad_test {
    }
}
