
-- ATM Offline MAPPING FILE FORMAT 

CREATE TABLE CMTXTFORMATUCFTYPE (TXTFORMATTYPE_CODE VARCHAR2(20) NOT NULL, TXTFORMATTYPE_DESC VARCHAR2(50) NOT NULL, TXTFILED_VALUE VARCHAR2(2), TXTREPLACE_VALUE VARCHAR2(2), TXTFORMAT VARCHAR2(50)) ;
ALTER TABLE CMTXTFORMATUCFTYPE ADD ( CONSTRAINT CMTXTFORMATUCFTYPE_PK PRIMARY KEY ( TXTFORMATTYPE_CODE )) ;

CREATE TABLE CMTXTFORMATMAS (TXTFORMAT_CODE VARCHAR2(20) NOT NULL, TXTFORMAT_DESC VARCHAR2(50) NOT NULL, TXTFORMAT_FILENAME VARCHAR2(50), BANK_CODE CHAR(3) DEFAULT '006' NOT NULL, LOANTYPE_CODE CHAR(2) DEFAULT '88' NOT NULL, DEPTTYPE_CODE CHAR(2) DEFAULT '88' NOT NULL) ;
ALTER TABLE CMTXTFORMATMAS ADD ( CONSTRAINT CMTXTFORMATMAS_PK PRIMARY KEY ( TXTFORMAT_CODE )) ;

CREATE TABLE CMTXTFORMATHEADER (TXTFORMAT_CODE VARCHAR2(20) NOT NULL, TXTFORMATHD_NM VARCHAR2(150) NOT NULL, SEQ_NO NUMBER(2,0) NOT NULL, TXTFORMATTYPE_CODE VARCHAR2(20) NOT NULL, TXTFORMAT_DESC VARCHAR2(150) NOT NULL, TXTLENG NUMBER(3,0) NOT NULL, FILLVALUE_FLAG NUMBER(1,0) DEFAULT 1 NOT NULL, FILLVALUE_DATA VARCHAR2(5), FORMATE_EXAMPLE VARCHAR2(150), TXTFILED_VALUE VARCHAR2(1), TXTDEFAULT_VALUE VARCHAR2(150), FORMATE_VALUE VARCHAR2(1000), TXTSTARTPOS NUMBER(3,0) DEFAULT 0 NOT NULL, TXTGROUP NUMBER(3,0) DEFAULT 1 NOT NULL) ;
ALTER TABLE CMTXTFORMATHEADER ADD ( CONSTRAINT CMTXTFORMATHEADER_PK PRIMARY KEY ( TXTFORMAT_CODE, TXTFORMATHD_NM, SEQ_NO )) ;

CREATE TABLE CMTXTFORMATFOOTER (TXTFORMAT_CODE VARCHAR2(20) NOT NULL, TXTFORMATFT_NM VARCHAR2(150) NOT NULL, SEQ_NO NUMBER(2,0) NOT NULL, TXTFORMATTYPE_CODE VARCHAR2(20) NOT NULL, TXTFORMAT_DESC VARCHAR2(150) NOT NULL, TXTLENG NUMBER(3,0) NOT NULL, FILLVALUE_FLAG NUMBER(1,0) DEFAULT 1 NOT NULL, FILLVALUE_DATA VARCHAR2(5), FORMATE_EXAMPLE VARCHAR2(150), TXTFILED_VALUE VARCHAR2(1), TXTDEFAULT_VALUE VARCHAR2(150), FORMATE_VALUE VARCHAR2(1000), TXTSTARTPOS NUMBER(3,0) DEFAULT 0 NOT NULL, TXTGROUP NUMBER(3,0) DEFAULT 1 NOT NULL) ;
ALTER TABLE CMTXTFORMATFOOTER ADD ( CONSTRAINT CMTXTFORMATFOOTER_PK PRIMARY KEY ( TXTFORMAT_CODE, TXTFORMATFT_NM, SEQ_NO )) ;

CREATE TABLE CMTXTFORMATDETAIL (TXTFORMAT_CODE VARCHAR2(20) NOT NULL, TXTFORMATDT_NM VARCHAR2(150) NOT NULL, SEQ_NO NUMBER(2,0) NOT NULL, TXTFORMATTYPE_CODE VARCHAR2(20) NOT NULL, TXTFORMAT_DESC VARCHAR2(150) NOT NULL, TXTLENG NUMBER(3,0) NOT NULL, FILLVALUE_FLAG NUMBER(1,0) DEFAULT 1 NOT NULL, FILLVALUE_DATA VARCHAR2(5), FORMATE_EXAMPLE VARCHAR2(150), TXTFILED_VALUE VARCHAR2(1), TXTDEFAULT_VALUE VARCHAR2(150), FORMATE_VALUE VARCHAR2(1000), TXTSTARTPOS NUMBER(3,0) DEFAULT 0 NOT NULL, TXTGROUP NUMBER(3,0) DEFAULT 1 NOT NULL) ;
ALTER TABLE CMTXTFORMATDETAIL ADD ( CONSTRAINT CMTXTFORMATDETAIL_PK PRIMARY KEY ( TXTFORMAT_CODE, TXTFORMATDT_NM, SEQ_NO )) ;

-- ATM Offline MAPPING FILE FORMAT 
