//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saving.Applications.keeping {
    
    
    public partial class w_sheet_kp_adjust_keepother_ins {
        
        /// <summary>
        /// DwMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sybase.DataWindow.Web.WebDataWindowControl DwMain;
        
        /// <summary>
        /// DwDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sybase.DataWindow.Web.WebDataWindowControl DwDetail;
    }
}
