//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saving.Applications.mbshr_const.ws_mb_ucfprovince_ctrl {
    
    
    public partial class ws_mb_ucfprovince {
        
        /// <summary>
        /// wd_list control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.mbshr_const.ws_mb_ucfprovince_ctrl.wd_list wd_list;
    }
}
