--------------------------------------------------------
--  File created - Tuesday-June-21-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATM_FIN_AMT
--------------------------------------------------------

  CREATE TABLE "ATM_FIN_AMT" 
   (	"SEQNO" NUMBER, 
	"REFNO" VARCHAR2(15), 
	"FINTYPE" CHAR(1), 
	"ACCNO" VARCHAR2(15), 
	"ITEMTYPE" CHAR(2), 
	"ITEMAMT" NUMBER(17,5), 
	"OPERATEDATE" DATE, 
	"MEMNO" VARCHAR2(8), 
	"MEMNM" VARCHAR2(60), 
	"MEMSNM" VARCHAR2(60), 
	"PERSONID" CHAR(13), 
	"BALAMT" NUMBER(17,5), 
	"STS" NUMBER(2,0), 
	"ISHOLD" CHAR(1), 
	"ISPOST" CHAR(1), 
	"POSTDATE" DATE, 
	"STAMPDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKATM_FINANCE_AMOUNT
--------------------------------------------------------

  CREATE UNIQUE INDEX "XPKATM_FINANCE_AMOUNT" ON "ATM_FIN_AMT" ("SEQNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ATM_FIN_AMT
--------------------------------------------------------

  ALTER TABLE "ATM_FIN_AMT" ADD CONSTRAINT "XPKATM_FINANCE_AMOUNT" PRIMARY KEY ("SEQNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ATM_FIN_AMT" MODIFY ("REFNO" NOT NULL ENABLE);
  ALTER TABLE "ATM_FIN_AMT" MODIFY ("SEQNO" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger ATMFINAMT_A_I
--------------------------------------------------------
CREATE SEQUENCE  ATMFINAMT_SEQ  MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20  ;
