drop database link COOPSERV.REGRESS.RDBMS.DEV.US.ORACLE.COM;
CREATE DATABASE LINK "COOPSERV.REGRESS.RDBMS.DEV.US.ORACLE.COM" CONNECT TO "SCOSRK" IDENTIFIED BY scosrk USING '127.0.0.1/scodat';
create or replace synonym PKG_ATMMGMT for SCOSRK.PKG_ATMMGMT@COOPSERV.REGRESS.RDBMS.DEV.US.ORACLE.COM;
create or replace synonym LOAN_MGMT for SCOSRK.LOAN_MGMT@COOPSERV.REGRESS.RDBMS.DEV.US.ORACLE.COM;
create or replace synonym DEPT_MGMT for SCOSRK.DEPT_MGMT@COOPSERV.REGRESS.RDBMS.DEV.US.ORACLE.COM;
create or replace synonym ATMCONFIG for SCOSRK.ATMCONFIG@COOPSERV.REGRESS.RDBMS.DEV.US.ORACLE.COM;
ALTER PACKAGE CORECOOP.PKG_ATMMGMT2 COMPILE BODY; 
