--------------------------------------------------------
--  File created - Tuesday-June-21-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATM_POST_SCSS
--------------------------------------------------------

  CREATE TABLE "ATM_POST_SCSS" 
   (	"SEQNO" NUMBER, 
	"REFNO" VARCHAR2(15), 
	"FINTYPE" CHAR(1), 
	"ACCNO" VARCHAR2(15), 
	"ITEMTYPE" CHAR(2), 
	"ITEMAMT" NUMBER(17,5), 
	"OPERATEDATE" DATE, 
	"MEMNO" CHAR(6), 
	"MEMNM" VARCHAR2(60), 
	"MEMSNM" VARCHAR2(60), 
	"PERSONID" CHAR(13), 
	"BALAMT" NUMBER(17,5), 
	"STS" NUMBER(2,0), 
	"ISHOLD" CHAR(1), 
	"ISPOST" CHAR(1), 
	"POSTDATE" DATE, 
	"STAMPDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKATM_POST_SUCCESS
--------------------------------------------------------

  CREATE UNIQUE INDEX "XPKATM_POST_SUCCESS" ON "ATM_POST_SCSS" ("SEQNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ATM_POST_SCSS
--------------------------------------------------------

  ALTER TABLE "ATM_POST_SCSS" ADD CONSTRAINT "XPKATM_POST_SUCCESS" PRIMARY KEY ("SEQNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ATM_POST_SCSS" MODIFY ("REFNO" NOT NULL ENABLE);
  ALTER TABLE "ATM_POST_SCSS" MODIFY ("SEQNO" NOT NULL ENABLE);
